version: 0.0
os: linux
files:
  - source: website
    destination: /var/www/html/website/
    overwrite: true
    fileExistsBehavior: OVERWRITE

hooks:
  AfterInstall:
    - location: scripts/restart_server.sh
      timeout: 300
      runas: root
